name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up Apache Maven Central
        uses: actions/setup-java@v1
        with: # running setup-java again overwrites the settings.xml
          java-version: 1.8
          server-id: releases # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: monkeyWie # env variable for username in deploy
          server-password: ${{ secrets.MAVEN_CENTRAL_TOKEN }} # env variable for token in deploy
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }} # env variable for GPG private key passphrase

      - name: Publish to Apache Maven Central
        run: mvn clean deploy -P release
        env:
          MAVEN_USERNAME: monkeyWie
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Release on nexus
        uses: monkeyWie/create-release@master
        with:
          maven-repo-server-username: monkeyWie
          maven-repo-server-password: ${{ secrets.MAVEN_CENTRAL_TOKEN }}